### PR TITLE
chore: remove `VERSION` for new pipelines

### PR DESCRIPTION
**Pull request by Xunzhuo**
Signed-off-by: Xunzhuo <mixdeers@gmail.com>

resolve: https://github.com/mosn/layotto/issues/521

remove `VERSION` for new pipelines, we use git describe to get latest git tag, we do not need it anymore.

### CODE REVIEW

**Comment by seeflood** [comment]
I just found a problem with version. 
Layotto used compilation flags to modify the [`Version` variable in main.go](https://github.com/mosn/layotto/blob/9a040f9842312bb6bddb09347e4d77cc6b4ddab9/cmd/layotto/main.go#L176) and :
image
But we removed the flags in new CI , which leads to some issues. 
For example, if you run the layotto binary, there's no version information in the printed message:
image

**Comment by Xunzhuo** [comment]
Easy fix, I will start a PR to fix it later:)

**Comment by seeflood** [comment]
Ok. Let's record it in a new issue and merge this PR

**Review by seeflood — APPROVED** [review]
lgtm

**Comment by Xunzhuo** [comment]
https://github.com/mosn/layotto/pull/516 Can we merge this PR first, this is related to publish amd64 image.

**Review by JervyShi — APPROVED** [review]
LGTM

**Pull request merged**
