### PR TITLE
fix: Publish subscription caused by metadata does not fill in caused …

### PR DESCRIPTION
**Pull request by akkw**
…by painc

**What this PR does**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by seeflood — APPROVED** [review]
lgtm

**Review by seeflood — APPROVED** [review]
lgtm

**Comment by seeflood** [comment]
Currently we can ignore the codecov error because the new CI doesn't run UT, see #529

**Review by JervyShi — APPROVED** [review]
LGTM

**Pull request merged**
