### PR TITLE
fix: optimize custom component initialization

### PR DESCRIPTION
**Pull request by wenxuwan**
**What this PR does**:

customer component should register when user configured  

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by Xunzhuo** [comment]
Suggest using draft PR as a WIP state.

**Comment by wenxuwan** [comment]
> Suggest using draft PR as a WIP state.

ok, it's ready for cr now

**Comment by Xunzhuo** [comment]
/lgtm
/approve

Thanks

**Pull request merged**
