### PR TITLE
chore: add demo code for delay queue API, using chatGPT

### PR DESCRIPTION
**Pull request by seeflood**
**What this PR does**:
It's an experiment to generate gRPC demo code using chatGPT

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by Xunzhuo — COMMENTED** [review]
Test cmds.

**Review by Xunzhuo — DISMISSED** [review]

**Comment by wenxuwan** [comment]
@Xunzhuo xunzhuo，能否提个issue或者pr来说明一下每个命令的作用和意义😄😄

**Comment by Xunzhuo** [comment]
OK。我今天弄 @wenxuwan

**Review by Xunzhuo — APPROVED** [review]
/lgtm

**Pull request merged**
