### PR TITLE
ci: reopen unit test checks and fix fatal

### PR DESCRIPTION
**Pull request by Xunzhuo**
Signed-off-by: Xunzhuo <mixdeers@gmail.com>

**What this PR does**:

ci: reopen unit test checks and fix fatal

Test cases in below packages:

@echo "===========> Run unit test in sdk/go-sdk"
@echo "===========> Run unit test in components"
@echo "===========> Run unit test in pkg"
@echo "===========> Run unit test in diagnostics"

resolve: https://github.com/mosn/layotto/issues/529

### CODE REVIEW

**Comment by Xunzhuo** [comment]
Only this test case failed TestPublishEvent, I did not see this failure https://github.com/mosn/layotto/issues/528

**Comment by Xunzhuo** [comment]
image

**Review by seeflood — DISMISSED** [review]
LGTM.

**Comment by seeflood** [comment]
@Xunzhuo I just found this issue with same error https://github.com/json-iterator/go/issues/608
It's beacuse current json-iterator version is incompatible with go 1.18

**Comment by Xunzhuo** [comment]
> @Xunzhuo I just found this issue with same error [json-iterator/go#608](https://github.com/json-iterator/go/issues/608) It's beacuse current json-iterator version is incompatible with go 1.18

Yes, it should be an issue in jsoniter, but I think layotto is using go 1.14?

**Comment by seeflood** [comment]
Yes, layotto use 1.14 because mosn use 1.14

**Comment by Xunzhuo** [comment]
> Yes, layotto use 1.14 because mosn use 1.14

I tried to upgrade jsoniter to 1.12, the fatal disappeared. We can keep jsoniter again, since it is with more high performance.

**Comment by Xunzhuo** [comment]
see https://github.com/mosn/layotto/pull/546/commits/eba64430d5b7d4ad4884388a815b94133fd65d08

**Review by seeflood — APPROVED** [review]
lgtm

**Review by ZLBer — APPROVED** [review]

**Pull request merged**
