### PR TITLE
feat: add js document

### PR DESCRIPTION
**Pull request by LZHK1ng**

### CODE REVIEW

**Comment by seeflood** [comment]
@LZHK1ng Thanks! Please sign the CLA first

**Review by seeflood — APPROVED** [review]
lgtm. Thanks for your contribution and welcome to the community !

**Review by zhenjunMa — APPROVED** [review]

**Comment by seeflood** [comment]
@LZHK1ng Sorry, we found that the demo failed 😢 
Could u help fix it ?
https://github.com/mosn/layotto/actions/runs/3247071797/jobs/5326577577
image

**Comment by seeflood** [comment]
> @LZHK1ng Sorry, we found that the demo failed 😢 Could u help fix it ? https://github.com/mosn/layotto/actions/runs/3247071797/jobs/5326577577 

I know why. Let me fix it

**Comment by seeflood** [comment]
@LZHK1ng Sorry, I don't know how to fix it, so I reverted this PR 😢 Could u submit this pr again and fix the CI error?

**Comment by LZHK1ng** [comment]
Ok, I will fix it.

**Pull request merged**
