### PR TITLE
chore: clean-up workflows

### PR DESCRIPTION
**Pull request by Xunzhuo**
**What this PR does**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by Xunzhuo — COMMENTED** [review]
/cc @Xunzhuo 
/area ci

**Review by wenxuwan — APPROVED** [review]
lgtm

**Review by seeflood — APPROVED** [review]
lgtm

**Pull request merged**
