### PR TITLE
feat: upgrade golang version to 1.18

### PR DESCRIPTION
**Pull request by wenxuwan**
**What this PR does**:

upgrade golang version to 1.18

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by seeflood — COMMENTED** [review]
Do we need to upgrade mosn first?

**Review by nejisama — APPROVED** [review]

**Comment by wenxuwan** [comment]
> Do we need to upgrade mosn first?

No，Mosn will upgrade later

**Comment by nejisama** [comment]
> Do we need to upgrade mosn first?

mosn upgrade need this

**Review by seeflood — APPROVED** [review]
lgtm

**Pull request merged**
