### PR TITLE
docs: secret demo

### PR DESCRIPTION
**Pull request by fft0518**
Add java sdk secret demo docs.

### CODE REVIEW

**Comment by seeflood** [comment]
@fft0518 thanks! Please sign the CLA first

**Comment by fft0518** [comment]
> 

Thanks. I have signed it.

**Comment by seeflood** [comment]
@fft0518 Hi, please fix the markdown issues reported by CI
image

**Comment by fft0518** [comment]
> @fft0518 Hi, please fix the markdown issues reported by CI image

Ok，I have fixed it.

**Comment by fft0518** [comment]
All checks have passed @seeflood.

**Review by seeflood — APPROVED** [review]
lgtm. Thanks

**Review by zhenjunMa — APPROVED** [review]

**Pull request merged**
