### PR TITLE
docs: add demo deploy k8s standalone yaml.

### PR DESCRIPTION
**Pull request by kevinten10**
**What this PR does**:

Make deploy `layotto` to `k8s` easily.

**Which issue(s) this PR fixes**:

Fixes https://github.com/mosn/layotto/issues/722

**Special notes for your reviewer**:

I will update docs.

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by seeflood — APPROVED** [review]
LGTM. It's very helpful. Thanks!

**Review by Xunzhuo — APPROVED** [review]
Looks good

**Comment by Xunzhuo** [comment]
Let us not merge this first, I will have a try and see if anything is missing.

**Comment by Xunzhuo** [comment]
image

**Comment by Xunzhuo** [comment]
It seems like that it works fine, thanks @kevinten10

**Pull request merged**
