### PR TITLE
ci: run dead link checker when there are markdown files been modified

### PR DESCRIPTION
**Pull request by seeflood**
**What this PR does**:
run dead link checker when there are markdown files been modified

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by seeflood** [comment]
@Xunzhuo How about this idea? Only run the checker when the markdown file is modified.
Actually I was testing AI's ability to write yaml. This yaml were written by AI and I'm not sure if it's correct...

**Comment by Xunzhuo** [comment]
/hold

Remove hold after CI passed.

**Comment by Xunzhuo** [comment]
/hold cancel

Thanks @seeflood, it looks good!

**Pull request merged**
