### PR TITLE
fix: update module name and format

### PR DESCRIPTION
**Pull request by Xunzhuo**
Signed-off-by: Xunzhuo <mixdeers@gmail.com>

fix and format codes.

No code changes in this PR, just format codes with the correct module name:)

resolve: https://github.com/mosn/layotto/issues/535

### CODE REVIEW

**Comment by Xunzhuo** [comment]
Let us get this merged ? This is no harmful to codes, just goimports style format:) cc @seeflood @mosn/committer

**Review by seeflood — DISMISSED** [review]
lgtm

**Comment by seeflood** [comment]
Oh, please fix the conflict

**Comment by Xunzhuo** [comment]
> Oh, please fix the conflict.

Confilcts have been resolved.

**Review by seeflood — APPROVED** [review]
lgtm

**Review by zhenjunMa — APPROVED** [review]

**Pull request merged**
