### PR TITLE
doc: modify community promotion rules

### PR DESCRIPTION
**Pull request by seeflood**
**What this PR does**:
modify committer promotion rules

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by Xunzhuo — APPROVED** [review]
lgtm

**Review by nobodyiam — APPROVED** [review]
Looks okay to me.

**Review by wenxuwan — APPROVED** [review]
LGTM

**Comment by seeflood** [comment]
@ZLBer @MoonShining @zhenjunMa Look here! 
Give me more approves!

**Review by zhenjunMa — APPROVED** [review]

**Review by stulzq — APPROVED** [review]

**Comment by stulzq** [comment]
LGTM

**Pull request merged**
