### PR TITLE
add license file for file

### PR DESCRIPTION
**Pull request by wenxuwan**
add license info for file and fix https://github.com/mosn/layotto/issues/240

### CODE REVIEW

**Comment by wenxuwan** [comment]
@seeflood please review the document

**Review by seeflood — DISMISSED** [review]

**Comment by seeflood** [comment]
Some other issues of existing documents:
1. Wrong descriptions in design doc,see https://mosn.io/layotto/#/zh/design/file/file-design  
Actually these listed interfaces are component interfaces,not grpc API
image

**Comment by seeflood** [comment]
2. Wrong links in the sidebar,see https://mosn.io/layotto/#/zh/component_specs/file/oss
The Etcd and Apollo docs are mis-configurated here
image

**Comment by seeflood** [comment]
@zach030 Hi,since @wenxuwan  is adding documents for File API,could u help review this PR and give some advice on File API documents?

**Review by MoonShining — APPROVED** [review]

**Pull request merged**
