### PR TITLE
feat: add file api impl tencent cloud oss

### PR DESCRIPTION
**Pull request by stulzq**

### CODE REVIEW

**Review by seeflood — CHANGES_REQUESTED** [review]

**Review by seeflood — CHANGES_REQUESTED** [review]
The code looks okay to me.Thanks for your contribution !

Could u please add more tests to make the [test coverage of `oss.go`](https://app.codecov.io/gh/mosn/layotto/compare/394/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr%20comments&utm_term=mosn#diff-Y29tcG9uZW50cy9maWxlL3MzL3RlbmNlbnRjbG91ZC9vc3MuZ28=) higher?
I will modify the codecov configuration to ignore those of `components/rpc/invoker/mosn/channel/xchannel.go` and `components/configstores/apollo/change_listener.go`

**Comment by stulzq** [comment]
> The code looks okay to me.Thanks for your contribution !
> 
> Could u please add more tests to make the [test coverage of `oss.go`](https://app.codecov.io/gh/mosn/layotto/compare/394/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr%20comments&utm_term=mosn#diff-Y29tcG9uZW50cy9maWxlL3MzL3RlbmNlbnRjbG91ZC9vc3MuZ28=) higher? I will modify the codecov configuration to ignore those of `components/rpc/invoker/mosn/channel/xchannel.go` and `components/configstores/apollo/change_listener.go`

No problem

**Review by wenxuwan — APPROVED** [review]
LGTM

**Review by seeflood — APPROVED** [review]
lgtm

**Pull request merged**
