### PR TITLE
chore: set deadlink validation to schedule, move out of PRs

### PR DESCRIPTION
**Pull request by Xunzhuo**
Signed-off-by: Xunzhuo <bitliu@tencent.com>

chore: set deadlink validation to schedule, move out of PRs

### CODE REVIEW

**Comment by seeflood** [comment]
belows are copied from dingtalk chat:
我观察了下误报，除了1例误报是美团的链接，其他报错 好像都是阿里云官网的链接，怀疑是被拦截了
要不，先在 deadlink 的配置里忽略掉阿里云官网的链接、观察一下？如果还是频繁误报 再改成 schedule 
因为提 PR 后跑这个检查，还是能发现挺多问题的（比如上次那个 cmd/xxx/xxx.proto )
当然，最理想的办法是改下这个工具：提 pr 时，只扫描发生了变更的文件、没变更的文件不扫描

**Review by seeflood — APPROVED** [review]
lgtm

**Comment by seeflood** [comment]
@Xunzhuo By the way, how do we know if the cron job failed? Will the job notify us by sending emails or submitting an issue?

**Review by wenxuwan — APPROVED** [review]

**Comment by Xunzhuo** [comment]
https://github.com/mosn/layotto/actions/workflows/dead-link-checker.yaml

we can check it here

**Comment by Xunzhuo** [comment]
And I think if we choose to watch this repo, ci failed should be notified by email, but not test yet.

**Pull request merged**
