### PR TITLE
chore: add comments using chatGPT

### PR DESCRIPTION
**Pull request by seeflood**
**What this PR does**:
Add comments using chatGPT.
This is an experiment.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by zhenjunMa — APPROVED** [review]

**Review by Xunzhuo — COMMENTED** [review]
/lgtm Thanks @seeflood

**Review by Xunzhuo — APPROVED** [review]

**Pull request merged**
