### PR TITLE
fix broken link

### PR DESCRIPTION
**Pull request by novahe**
**What this PR does**:
/kind cleanup

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zhenjunMa** [comment]
@novahe sorry to bother you, but, before merge your pr, please sign the CLA like @mosn-community-bot comment, thanks

**Comment by novahe** [comment]
I sign it @mosn-community-bot

**Comment by novahe** [comment]
I sign it @mosn-community-bot

**Review by zhenjunMa — APPROVED** [review]
LGTM

**Comment by zhenjunMa** [comment]
@novahe  i have reviewed, thanks!

**Pull request merged**
