### PR TITLE
add bindings for layotto

### PR DESCRIPTION
**Pull request by wenxuwan**
import bindings for layotto

### CODE REVIEW

**Comment by seeflood** [comment]
hi,@stulzq  @MoonShining  @ZLBer could u help review this pr?

**Comment by seeflood** [comment]
Thanks for your contribution!
Could u please add some docs?

**Review by MoonShining — APPROVED** [review]
LGTM

**Comment by wenxuwan** [comment]
> Thanks for your contribution! Could u please add some docs?

document will be add later as the feature just import dapr component

**Pull request merged**
