### PR TITLE
remove invalid characters

### PR DESCRIPTION
**Pull request by liubin**
**What this PR does**:

The original file encoding is ISO-8859-1 and some(Chinese) characters are invalid. This PR will remove the invalid characters and replaced them with the correct ASCII characters.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by seeflood** [comment]
> **What this PR does**:
> 
> The original file encoding is ISO-8859-1 and some(Chinese) characters are invalid. This PR will remove the invalid characters and replaced them with the correct ASCII characters.
> 
> **Which issue(s) this PR fixes**:
> 
> Fixes #
> 
> **Special notes for your reviewer**:
> 
> **Does this PR introduce a user-facing change?**:
> 
> ```
> 
> ```

@liubin Thanks for your contribution!
We just fixed a CI bug which leads to a github action error.So please merge the main branch first and then we can run the workflow

**Comment by liubin** [comment]
@seeflood I have merged the latest main branch, can you let CI run?

**Comment by zhenjunMa** [comment]
@liubin  sorry to bother you, but, before merge your pr, please sign the CLA like @mosn-community-bot comment, thanks

**Comment by liubin** [comment]
Close this one to enable CLA check.

**Pull request closed without merging**
