### PR TITLE
Add optional properties for topic event while maintaining backward co…

### LINKED ISSUE #183: [Proposal] Add metadata for TopicEventRequest
**What would you like to be added**:

Add an optional metadata map to TopicEventRequest message to pass some extra properties during message delivery.

```
message TopicEventRequest {
  string id = 1;

  string source = 2;

  string type = 3;

  string spec_version = 4;

  string data_content_type = 5;

  bytes data = 7;

  string topic = 6;

  string pubsub_name = 8;
  // add a map to pass some extra properties.
  map<string,string> metadata = 9;
}
```

**Why is this needed**:

In some messaging systems, existing TopicEventRequest message lacks a flexible field to pass some extra properties.

### PR DESCRIPTION
**Pull request by RayneHwang**
**What this PR does**:
Add an optional metadata map to TopicEventRequest message to pass some extra properties during message delivery.

**Which issue(s) this PR fixes**:

Fixes #183

**Special notes for your reviewer**:
This pull request does not break compatibility.

**Does this PR introduce a user-facing change?**:
NONE

### CODE REVIEW

**Comment by seeflood** [comment]
Hi,are u still working on it ?

**Comment by seeflood** [comment]
There are always some fields need to be passed in real word, such as the `offset` field in Kafka.
This pr add a metadata field for users to pass these custom fields. It will make Layotto pubsub API different from Dapr's,but we are communicating with Dapr community to add this field.see https://github.com/dapr/dapr/issues/3276

**Comment by RayneHwang** [comment]
> Hi,are u still working on it ?

merged upstream changes from mosn/layotto:main to resolve conflicts

**Comment by seeflood** [comment]
@RayneHwang hi,I'm afraid that u miss some fields in this proto,e.g. `path` in `TopicEventRequest`

**Pull request closed without merging**
